let input=document.querySelector("input");

// input.addEventListener("keyup",function(){
//     console.log("key is up ");
// })

// input.addEventListener("keydown",function(){
//     console.log("key was pressed");
// });


// keyboard event =>
    // **key => Refers to the actual character or action generated by the key.
    //example=>
    //  With CapsLock off → "a"
    //With Shift pressed → "A"
    //Pressing Enter → "Enter"

    // **code => Refers to the physical key position on the keyboard.
    //example =>
    // if pressed A event.code = "KeyA"
    // if pressed 1 event.code= "Digit1"

    input.addEventListener("keydown", function (event) {
  console.log("code = ", event.code); 
  // ArrowUp(U), ArrowDown(D), ArrowLeft(L), ArrowRight(R)

  if (event.code === "KeyU") {
    console.log("character moves up");
  } else if (event.code === "KeyD") {
    console.log("character moves down");
  } else if (event.code === "KeyL") {
    console.log("character moves left");
  } else if (event.code === "KeyR") {
    console.log("character moves right");
  }
});